# Generated by Django 4.0.4 on 2022-07-06 11:06

import avaliacao.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='aula_do_aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aula.auladoaluno'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='checklist',
            field=models.JSONField(default=avaliacao.models.Avaliacao.default_checklist, verbose_name='checklist'),
        ),
    ]
