# Generated by Django 4.0.4 on 2022-04-11 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aula', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.JSONField(verbose_name='checklist')),
                ('aula_do_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.auladoaluno')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.administrador')),
                ('idArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.area')),
                ('idAvaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.avaliacao')),
            ],
        ),
    ]
