# Generated by Django 4.0.4 on 2022-04-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.JSONField(verbose_name='checklist')),
                ('aula_do_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.auladoaluno')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatorio', models.TextField(max_length=2000, verbose_name='Relatório')),
                ('idAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.administrador', verbose_name='Administrador')),
                ('idArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.area', verbose_name='Area')),
                ('idAvaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.avaliacao', verbose_name='Avaliacao')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AvaliacoesDoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAvaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.avaliacao')),
                ('idRelatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.relatorio')),
            ],
        ),
    ]
