# Generated by Django 4.0.3 on 2022-04-11 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aula', '0002_initial'),
        ('relatorio', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='idAdmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.administrador', verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='idArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.area', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='idAvaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.avaliacao', verbose_name='Avaliacao'),
        ),
        migrations.AddField(
            model_name='avaliacoesdorelatorio',
            name='idAvaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.avaliacao'),
        ),
        migrations.AddField(
            model_name='avaliacoesdorelatorio',
            name='idRelatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.relatorio'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='aula_do_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.auladoaluno'),
        ),
    ]
