# Generated by Django 4.0.4 on 2022-04-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='relatorio',
            field=models.CharField(default='', max_length=2000, verbose_name='Relatorio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='idAdmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.administrador', verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='idArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='idAvaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.avaliacao', verbose_name='Avaliacao'),
        ),
        migrations.CreateModel(
            name='AvaliacoesDoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAvaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.avaliacao')),
                ('idRelatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.relatorio')),
            ],
        ),
    ]
