# Generated by Django 4.0.4 on 2022-04-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0002_relatorio_relatorio_alter_relatorio_idadmin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='relatorio',
            field=models.TextField(max_length=2000, verbose_name='Relatório'),
        ),
    ]
