# Generated by Django 4.0.4 on 2022-06-22 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, default=2022, null=True, verbose_name='Ano da Turma')),
                ('periodo', models.IntegerField(blank=True, default=1, null=True, verbose_name='Período da Turma')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição, Código...')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disciplina.disciplina', verbose_name='Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.professor', verbose_name='Professor')),
            ],
            options={
                'ordering': ('-disciplina',),
            },
        ),
    ]
