# Generated by Django 4.0.4 on 2022-06-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ('-disciplina',)},
        ),
        migrations.AddField(
            model_name='turma',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição, Código...'),
        ),
    ]
