# Generated by Django 4.0.4 on 2022-06-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0002_remove_disciplina_idprofessor'),
        ('turma', '0002_alter_turma_options_turma_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disciplina.disciplina', verbose_name='Disciplina'),
        ),
    ]
