# Generated by Django 4.0.4 on 2022-06-09 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('disciplina', '0002_remove_disciplina_idprofessor'),
        ('turma', '0003_alter_turma_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disciplina.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.professor', verbose_name='Professor'),
        ),
    ]
