# Generated by Django 4.0.4 on 2022-08-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto da aula')),
                ('datetime', models.DateTimeField(verbose_name='Data e Hora da Aula')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turma.turma', verbose_name='Turma')),
            ],
            options={
                'ordering': ('datetime',),
            },
        ),
    ]
