# Generated by Django 4.0.4 on 2022-04-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='auladoaluno',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='aula',
            name='assunto',
            field=models.CharField(default='', max_length=50, verbose_name='Assunto da aula'),
            preserve_default=False,
        ),
    ]
