# Generated by Django 4.0.4 on 2022-04-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aula', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auladoaluno',
            name='idAluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.aluno'),
        ),
        migrations.AddField(
            model_name='auladoaluno',
            name='idAula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.aula'),
        ),
        migrations.AddField(
            model_name='aula',
            name='idArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.area'),
        ),
        migrations.AddField(
            model_name='aula',
            name='idProfessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professor'),
        ),
    ]
