# Generated by Django 4.0.4 on 2022-06-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_alter_turma_options_turma_descricao'),
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ('-turma',)},
        ),
        migrations.RemoveField(
            model_name='aula',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='turma.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='assunto',
            field=models.CharField(max_length=255, null=True, verbose_name='Assunto da aula'),
        ),
    ]
