# Generated by Django 4.0.4 on 2022-05-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='idProfessor',
        ),
        migrations.AddField(
            model_name='aula',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disciplina.disciplina', verbose_name='Disciplina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aula',
            name='datetime',
            field=models.DateTimeField(verbose_name='Data e Hora da Aula'),
        ),
    ]
