# Generated by Django 4.0.4 on 2022-05-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auladoaluno',
            name='idAluno',
        ),
        migrations.RemoveField(
            model_name='auladoaluno',
            name='idAula',
        ),
        migrations.AddField(
            model_name='auladoaluno',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='auladoaluno',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aula.aula', verbose_name='Aula'),
        ),
    ]
