# Generated by Django 4.0.4 on 2022-05-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_aluno_matricula'),
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='assunto',
            field=models.CharField(max_length=255, verbose_name='Assunto da aula'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='idArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.area', verbose_name='Área'),
        ),
    ]
