# Generated by Django 4.0.4 on 2022-08-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_alter_aula_assunto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ('datetime',)},
        ),
        migrations.AddField(
            model_name='auladoaluno',
            name='presenca',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Presença'),
        ),
    ]
