# Generated by Django 4.0.4 on 2022-06-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_alter_aula_options_remove_aula_disciplina_aula_turma_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auladoaluno',
            old_name='idAluno',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='auladoaluno',
            old_name='idAula',
            new_name='aula',
        ),
    ]
