# Generated by Django 4.0.4 on 2022-06-09 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0003_alter_turma_disciplina'),
        ('aula', '0003_rename_idaluno_auladoaluno_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turma.turma', verbose_name='Turma'),
        ),
    ]
