# Generated by Django 4.0.4 on 2022-08-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='matricula')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
            options={
                'ordering': ('-nome',),
            },
        ),
    ]
