# Generated by Django 4.0.4 on 2022-05-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='matricula'),
        ),
    ]
